// Guided meditation scripts — "at" is percentage of total time (0-1)
const MEDITATION_SCRIPTS = {
  breath: [
    { at: 0.00, text: "Close your eyes gently. Let your hands rest in your lap." },
    { at: 0.03, text: "Take a deep breath in through your nose... feel your chest expand." },
    { at: 0.06, text: "Now slowly exhale through your mouth. Let everything go." },
    { at: 0.09, text: "Again — breathe in deeply... filling your lungs completely." },
    { at: 0.12, text: "And release... feel the tension leaving your body." },
    { at: 0.15, text: "Now let your breathing find its natural rhythm. Don't force it." },
    { at: 0.19, text: "Notice where you feel each breath most — your nostrils, chest, or belly." },
    { at: 0.23, text: "Focus all your attention on that one spot. Feel each inhale arrive." },
    { at: 0.27, text: "Feel each exhale depart. Like waves on a shore." },
    { at: 0.31, text: "If your mind wanders — and it will — gently bring it back. No judgment." },
    { at: 0.35, text: "Each breath is an anchor. Inhale... you are here. Exhale... you are now." },
    { at: 0.39, text: "Notice the tiny pause between breaths. That still point of peace." },
    { at: 0.43, text: "Let each breath grow slightly deeper. Slightly slower." },
    { at: 0.47, text: "Your breath is always with you. A constant companion through life." },
    { at: 0.51, text: "Feel the cool air entering... and the warm air leaving." },
    { at: 0.55, text: "With every exhale, release one more worry. Let it float away." },
    { at: 0.59, text: "With every inhale, draw in calm. Draw in stillness." },
    { at: 0.63, text: "You are not your thoughts. You are the awareness behind them." },
    { at: 0.67, text: "Keep returning to the breath. Patient. Gentle. Always welcoming." },
    { at: 0.71, text: "Feel the rhythm of your body. Your own quiet music." },
    { at: 0.75, text: "Let your breath become effortless. It knows what to do." },
    { at: 0.79, text: "Notice how peaceful your body feels. How still your mind has become." },
    { at: 0.83, text: "You've been doing beautifully. Stay with this feeling." },
    { at: 0.87, text: "Begin to deepen your breath again. Slowly returning." },
    { at: 0.91, text: "Feel the surface beneath you. The room around you." },
    { at: 0.95, text: "Take one final deep breath... and gently open your eyes." },
    { at: 0.98, text: "Carry this calm with you. Namaste." },
  ],
  body_scan: [
    { at: 0.00, text: "Lie still or sit comfortably. Close your eyes." },
    { at: 0.03, text: "Take three slow, deep breaths to settle in." },
    { at: 0.06, text: "We'll gently scan through your body, noticing each area." },
    { at: 0.09, text: "Bring your attention to the top of your head. The crown." },
    { at: 0.12, text: "Feel any tingling or warmth there. Just notice. Don't change it." },
    { at: 0.15, text: "Now move to your forehead. Soften any furrows. Let it smooth out." },
    { at: 0.18, text: "Move to your eyes. Let them rest heavy in their sockets." },
    { at: 0.21, text: "Relax your jaw. Let your tongue drop from the roof of your mouth." },
    { at: 0.24, text: "Feel your neck and throat. Release any tightness you find there." },
    { at: 0.27, text: "Move to your shoulders. They carry so much — let them drop now." },
    { at: 0.30, text: "Scan down your right arm. Upper arm... forearm... hand... fingertips." },
    { at: 0.33, text: "Now your left arm. Upper arm... forearm... hand... fingertips." },
    { at: 0.36, text: "Feel your hands. Notice any warmth or pulsing in your palms." },
    { at: 0.39, text: "Bring attention to your chest. Feel it rise and fall." },
    { at: 0.42, text: "Notice your heartbeat. Steady. Faithful. Always working for you." },
    { at: 0.45, text: "Move to your upper back. Between the shoulder blades." },
    { at: 0.48, text: "Now your lower back. Breathe warmth into any stiff areas." },
    { at: 0.51, text: "Scan your belly. Let it be soft. No holding, no tensing." },
    { at: 0.54, text: "Notice your hips. The bowl of your pelvis. Let it be heavy." },
    { at: 0.57, text: "Move to your right thigh... knee... calf... foot... toes." },
    { at: 0.60, text: "Now your left thigh... knee... calf... foot... toes." },
    { at: 0.63, text: "Feel the soles of your feet. Your connection to the earth." },
    { at: 0.66, text: "Now expand your awareness to your whole body at once." },
    { at: 0.70, text: "Feel yourself as one complete, connected being. Whole and alive." },
    { at: 0.74, text: "Notice how different your body feels now compared to when we began." },
    { at: 0.78, text: "If any area still holds tension, breathe into it gently." },
    { at: 0.82, text: "Your body is your home. Thank it for carrying you through each day." },
    { at: 0.86, text: "Let this feeling of full-body awareness settle deep within you." },
    { at: 0.90, text: "Begin to wiggle your fingers and toes. Slowly awakening." },
    { at: 0.94, text: "Take a deep breath. Stretch gently if it feels right." },
    { at: 0.97, text: "Open your eyes when ready. You are refreshed and restored." },
  ],
  loving_kindness: [
    { at: 0.00, text: "Settle into a comfortable position. Close your eyes softly." },
    { at: 0.03, text: "Place your hand over your heart if it feels right." },
    { at: 0.06, text: "We'll cultivate feelings of warmth and love, starting with yourself." },
    { at: 0.09, text: "Picture yourself clearly. As you are right now." },
    { at: 0.12, text: "Silently repeat: May I be happy. May I be healthy." },
    { at: 0.15, text: "May I be safe. May I live with ease." },
    { at: 0.18, text: "Feel those words settle in. You deserve this kindness." },
    { at: 0.21, text: "Again: May I be happy... May I be healthy..." },
    { at: 0.24, text: "May I be safe... May I live with ease..." },
    { at: 0.27, text: "Now think of someone you love deeply. See their face clearly." },
    { at: 0.30, text: "Direct these wishes to them: May you be happy. May you be healthy." },
    { at: 0.33, text: "May you be safe. May you live with ease." },
    { at: 0.36, text: "Feel the warmth radiating from your heart toward them." },
    { at: 0.39, text: "Again: May you be happy... May you be healthy..." },
    { at: 0.42, text: "Now think of someone neutral — an acquaintance, a stranger you've seen." },
    { at: 0.45, text: "Send them the same kindness: May you be happy. May you be healthy." },
    { at: 0.48, text: "May you be safe. May you live with ease." },
    { at: 0.51, text: "Everyone you pass on the street has struggles you'll never see." },
    { at: 0.54, text: "Now — the hardest part. Think of someone difficult in your life." },
    { at: 0.57, text: "This doesn't mean you approve of their actions. Just let go of the weight." },
    { at: 0.60, text: "May you be happy. May you be healthy. May you be safe." },
    { at: 0.63, text: "Forgiveness is a gift you give yourself. Release what you can." },
    { at: 0.66, text: "Now expand outward. All beings everywhere." },
    { at: 0.69, text: "May all beings be happy. May all beings be healthy." },
    { at: 0.72, text: "May all beings be safe. May all beings live with ease." },
    { at: 0.75, text: "Feel yourself connected to every living thing. One web of life." },
    { at: 0.78, text: "Let this love radiate outward in all directions. Without limit." },
    { at: 0.82, text: "Return to yourself. Feel the warmth in your chest." },
    { at: 0.86, text: "You've just made the world a little softer with your intention." },
    { at: 0.90, text: "Take a deep breath. Let gratitude fill the space." },
    { at: 0.94, text: "Gently release the practice. Keep the feeling." },
    { at: 0.97, text: "Open your eyes. Carry this kindness into your day." },
  ],
  visualization: [
    { at: 0.00, text: "Close your eyes. Take a few deep breaths to arrive fully here." },
    { at: 0.03, text: "We're going on a journey. Let your imagination be vivid." },
    { at: 0.06, text: "Imagine you're standing at the edge of a quiet forest." },
    { at: 0.09, text: "The air is cool and fresh. Smell the pine and damp earth." },
    { at: 0.12, text: "A soft path stretches ahead, dappled with golden sunlight." },
    { at: 0.15, text: "Begin walking. Feel the soft ground beneath your feet." },
    { at: 0.18, text: "Hear birds singing high in the canopy. Leaves rustling gently." },
    { at: 0.21, text: "The trees grow taller. Light filters through in shimmering columns." },
    { at: 0.24, text: "You come to a stream. Clear water flowing over smooth stones." },
    { at: 0.27, text: "Kneel down. Cup the cool water in your hands. Drink." },
    { at: 0.30, text: "As you drink, feel it washing away stress and worry." },
    { at: 0.33, text: "Stand and continue. The path leads uphill now, gently." },
    { at: 0.36, text: "With each step, you feel lighter. Burdens falling away." },
    { at: 0.39, text: "The trees open up. You step into a sunlit meadow." },
    { at: 0.42, text: "Wildflowers sway in a warm breeze. Colors everywhere." },
    { at: 0.45, text: "Find a spot in the center. Lie down in the soft grass." },
    { at: 0.48, text: "Look up at the vast sky. Clouds drifting slowly." },
    { at: 0.51, text: "Each cloud carries a thought. Watch them float by without holding on." },
    { at: 0.54, text: "Feel the sun warming your face. The earth supporting your body." },
    { at: 0.57, text: "You are completely safe here. This place is yours." },
    { at: 0.60, text: "A gentle light begins to glow in your chest. Warm and golden." },
    { at: 0.63, text: "It grows brighter with each breath. Filling your whole body." },
    { at: 0.66, text: "This light is your strength. Your peace. Always inside you." },
    { at: 0.69, text: "Let it expand beyond your body. Into the meadow. Into the sky." },
    { at: 0.72, text: "You are connected to everything. Part of something immense and beautiful." },
    { at: 0.75, text: "Rest here for a moment. Feel the completeness of this place." },
    { at: 0.79, text: "Now slowly sit up. The meadow thanks you for visiting." },
    { at: 0.83, text: "Walk back down the path. The forest welcomes your return." },
    { at: 0.87, text: "The stream, the birds, the dappled light — all saying goodbye." },
    { at: 0.91, text: "You reach the forest edge. Take a deep breath of that pine air." },
    { at: 0.95, text: "Feel your body in this room. Fingers, toes. Slowly return." },
    { at: 0.98, text: "Open your eyes. The peace of the forest stays with you." },
  ],
  mindfulness: [
    { at: 0.00, text: "Sit comfortably. Let your eyes close or soften your gaze downward." },
    { at: 0.03, text: "Take three deep breaths. Arriving fully in this moment." },
    { at: 0.06, text: "Mindfulness is simple: notice what is, without wishing it different." },
    { at: 0.09, text: "Start with sounds. What can you hear right now? Near and far." },
    { at: 0.12, text: "Don't label them as good or bad. Just sounds arising and fading." },
    { at: 0.15, text: "Now notice physical sensations. Temperature on your skin. Weight in your seat." },
    { at: 0.18, text: "The feeling of fabric on your body. Air moving across your face." },
    { at: 0.21, text: "Notice without reacting. You are an observer, calm and curious." },
    { at: 0.24, text: "Now turn inward. What emotions are present? Name them gently." },
    { at: 0.27, text: "Anxious? Calm? Restless? Sad? Content? Just notice. All are welcome." },
    { at: 0.30, text: "Emotions are like weather. They pass through. You are the sky." },
    { at: 0.33, text: "Now observe your thoughts. Watch them like cars on a distant highway." },
    { at: 0.36, text: "You don't need to get in any car. Just watch them pass." },
    { at: 0.39, text: "When you catch yourself thinking, smile. You just became aware." },
    { at: 0.42, text: "That moment of noticing IS mindfulness. You're doing it perfectly." },
    { at: 0.45, text: "Return to your breath. The simplest anchor to now." },
    { at: 0.48, text: "This breath. This moment. This is all there ever really is." },
    { at: 0.51, text: "Expand your awareness. Hold everything at once — sounds, body, breath." },
    { at: 0.54, text: "This wide-open awareness. Spacious. Accepting. Peaceful." },
    { at: 0.58, text: "If discomfort arises, don't run from it. Lean in gently." },
    { at: 0.62, text: "Behind every discomfort is something asking to be seen. Be brave." },
    { at: 0.66, text: "Let go of the need to fix anything. Right now, nothing is broken." },
    { at: 0.70, text: "You are exactly where you need to be. Doing exactly enough." },
    { at: 0.74, text: "Feel the aliveness in your body. The miracle of simply being here." },
    { at: 0.78, text: "Every moment is fresh. Every breath is new. Nothing repeats." },
    { at: 0.82, text: "This ordinary moment IS the extraordinary life you've been given." },
    { at: 0.86, text: "Begin to bring your attention back. Gently, like waking from a nap." },
    { at: 0.90, text: "Notice the room. Sounds returning. The world welcoming you back." },
    { at: 0.94, text: "Take a deep, nourishing breath. Feel gratitude for this pause." },
    { at: 0.97, text: "Open your eyes. Bring this presence into whatever comes next." },
  ],
  mantra: [
    { at: 0.00, text: "Find a comfortable seat. Spine tall but not rigid. Eyes closed." },
    { at: 0.03, text: "Take three centering breaths. Arriving in stillness." },
    { at: 0.06, text: "Mantra meditation uses a repeated phrase to focus and calm the mind." },
    { at: 0.09, text: "Choose a mantra that resonates. Or use: \"I am at peace.\"" },
    { at: 0.12, text: "Begin repeating it silently. Slowly. With each exhale." },
    { at: 0.15, text: "I am at peace... I am at peace... I am at peace..." },
    { at: 0.18, text: "Let the words become a gentle rhythm. Like a heartbeat." },
    { at: 0.21, text: "Don't rush. Let each repetition be complete before the next." },
    { at: 0.24, text: "I am at peace... Feel the meaning of each word." },
    { at: 0.27, text: "\"I\" — acknowledging yourself, here, present." },
    { at: 0.30, text: "\"am\" — existing, alive, in this very moment." },
    { at: 0.33, text: "\"at peace\" — choosing calm. Claiming it as yours." },
    { at: 0.36, text: "Continue repeating. Let the mantra carry you deeper." },
    { at: 0.39, text: "I am at peace... I am at peace..." },
    { at: 0.42, text: "If thoughts interrupt, simply return to the words. No frustration." },
    { at: 0.45, text: "The mantra is a thread back to center. Always available." },
    { at: 0.48, text: "Let the repetition become almost automatic. Effortless." },
    { at: 0.51, text: "I am at peace... Feel it resonating in your chest." },
    { at: 0.54, text: "Some traditions say the mantra eventually repeats itself." },
    { at: 0.57, text: "You're not saying it — you're listening to it." },
    { at: 0.60, text: "I am at peace... I am at peace..." },
    { at: 0.63, text: "Let the spaces between repetitions grow. Savor the silence." },
    { at: 0.66, text: "In that silence between words, peace already exists." },
    { at: 0.69, text: "I am at peace... The words become softer now." },
    { at: 0.72, text: "Almost a whisper in your mind. Barely there." },
    { at: 0.75, text: "Let the mantra fade to silence if it wants to. That's okay." },
    { at: 0.78, text: "Sit in whatever remains. The feeling the words left behind." },
    { at: 0.82, text: "This is the fruit of practice — peace that needs no words." },
    { at: 0.86, text: "If the mantra returns, welcome it. If silence stays, welcome that." },
    { at: 0.90, text: "Begin to return. Feel your body. The room around you." },
    { at: 0.94, text: "Take a deep breath. Carry your mantra with you today." },
    { at: 0.97, text: "Open your eyes. I am at peace. And so it is." },
  ],
};

export function getMeditationPrompt(medTypeId, elapsed, totalSeconds) {
  const script = MEDITATION_SCRIPTS[medTypeId];
  if (!script) return "";
  const pct = elapsed / totalSeconds;
  let current = "";
  for (let i = 0; i < script.length; i++) {
    if (pct >= script[i].at) current = script[i].text;
    else break;
  }
  return current;
}

export { MEDITATION_SCRIPTS };
